### ISSUE TITLE
Interlaced video doesn't get generated in EDID properly

### ISSUE THREAD

**Issue by syboxez** [antonioginer/switchres#101]
When attempting to generate a 480i @ 60Hz EDID, I end up getting a 480p @ 60Hz result. Generating progressive modes works fine.

**Comment by substring** [comment]
Hi,

I thoroughly use that feature and have no problem. How dontou diagnose that 480p ? What's your OS and hardware ?

**Comment by syboxez** [comment]
> Hi,
> 
> I thoroughly use that feature and have no problem. How dontou diagnose that 480p ? What's your OS and hardware ?

OS: Arch Linux
Hardware: ASUS FA617NT laptop with AMD RX 7700S GPU using a USB-C alt mode to HDMI adapter + a Tendak HDMI to VGA DAC

So this seems to be yet another issue with my GPU. It works fine on my R9 380, but not my laptop (using a DAC) which has an RX 7700S. Usually interlaced video will output squashed horizontally on my laptop when using xrandr on an unpatched kernel, but using the EDID gets me 480p@60 (a side-by-side doubled image on my NTSC CRT).

Semi-relevant issue is open here: https://github.com/D0023R/linux_kernel_15khz/issues/11

IMO, this issue can be closed, as it doesn't seem to be an issue with SwitchRes.

**Comment by substring** [comment]
We have no idea how RX7xxx behave for now. But they will probably never
have interlaced

**Comment by syboxez** [comment]
> We have no idea how RX7xxx behave for now. But they will probably never have interlaced

Interlaced modes semi-function on an unpatched kernel when using xrandr. The output horizontally squished, but it is still interlaced and the image is complete, centered, and not doubled.

**Comment by antonioginer** [comment]
The squished output you see with unpatched kernel isn't interlaced, it's progressive. Patched kernel actually attempts to set interlace, but fails on DCN3 hardware (by now).

**Comment by syboxez** [comment]
> The squished output you see with unpatched kernel isn't interlaced, it's progressive. Patched kernel actually attempts to set interlace, but fails on DCN3 hardware (by now).

Oh interesting. What progressive resolution is being displayed if not 640x480@60Hz interlaced?

The image displayed on screen is an interlaced image @ 60 Fields Per Second.

**Comment by syboxez** [comment]
> The squished output you see with unpatched kernel isn't interlaced, it's progressive. Patched kernel actually attempts to set interlace, but fails on DCN3 hardware (by now).

DCN3 now supports interlacing thanks to D0023R's kernel patch. I can also confirm that interlaced EDID generation works fine.

**Comment by substring** [comment]
Well ... So you know ... Calamity wrote the patch, and doozer added it. We work all 3 hand in hand ;)

**Comment by syboxez** [comment]
> Well ... So you know ... Calamity wrote the patch, and doozer added it. We work all 3 hand in hand ;)

Well credit to all three of you then!

**Comment by D0023R** [comment]
Indeed, DCN interlaced fixes are from @Calamity. Good to hear that it works.
