### ISSUE TITLE
Debian 10 build compilation error

### ISSUE THREAD

**Issue by MiltosKoutsokeras** [antonioginer/switchres#85]
The project does not build under Debian 10 stable:

- GCC 8.30
- Binutils 2.31.1
- GLIBC 2.28
- libdrm 2.4.97-1
- libxrandr 1.5.1-1

with the following error message:
```
In file included from custom_video.cpp:27:
custom_video_drmkms.h:76:14: error: 'drmIsMaster' was not declared in this scope
   __typeof__(drmIsMaster) *p_drmIsMaster;
              ^~~~~~~~~~~
custom_video_drmkms.h:76:14: note: suggested alternative: 'drmSetMaster'
   __typeof__(drmIsMaster) *p_drmIsMaster;
              ^~~~~~~~~~~
              drmSetMaster
```

It looks like my version of libdrm has no `drmIsMaster` defintion. Opening issue to point out project is not compiling on Debian 10 right now. I will try to find a solution if possible and send a pull request.

**Comment by MiltosKoutsokeras** [comment]
It seems this definition was introduced after the Debian 10 libdrm 2.4.97, in commit 17dfe3ac93217b43f93bc81d1129bd38a89d0368: https://gitlab.freedesktop.org/mesa/drm/-/commit/17dfe3ac93217b43f93bc81d1129bd38a89d0368

```
commit 17dfe3ac93217b43f93bc81d1129bd38a89d0368
Author: Christopher James Halse Rogers <christopher.halse.rogers@canonical.com>
Date:   Wed Jan 23 15:38:45 2019 +1100
```

Which is one day (damn...) after the 2.4.97 tag: https://gitlab.freedesktop.org/mesa/drm/-/tags/libdrm-2.4.97

```
tag libdrm-2.4.97
Tagger: Marek Olšák <marek.olsak@amd.com>
Date:   Tue Jan 22 11:34:18 2019 -0500

libdrm-2.4.97
-----BEGIN PGP SIGNATURE-----

iQEzBAABCgAdFiEEzUfFNBo3XzO+97r6/dFdWs7w8rEFAlxHRgoACgkQ/dFdWs7w
8rHSJAf/TGjzqdfvF5p++fo12cQ+eYNAbeACqouJwGSP4uODl6w+PDktZKhHVISR
dQ7gqOnzEBbHTc4W52wvQOg3VqI3hL1BElQ8tAuWFwFzTBiSuyoUi7uwp0OYyQl9
84KXLWl/UngHHnj99z4QRoub4bLI/zHabPBgnkS+ScQ1sms0/fb9ikVRy+6qqmMz
zzKunwAeYo+EBPfpo0PMCibSYKG9hKPTNdmu8mgxarMVu6jsDoKaMDilJnbddVzv
+/eqYjaGHXJCN9fTbgcvP6MU3bX0TVKZ3lVco7uNZnwSUqAk1L9apNaYOpdIY8Pk
jh78nr/hrCPsaLhcHqC01z+aC1GhwA==
=AIDg
-----END PGP SIGNATURE-----

commit b7a7a90336fbb19efb3f91f92b5d964b0dfb7ec2 (tag: libdrm-2.4.97)
Author: Marek Olšák <marek.olsak@amd.com>
Date:   Tue Jan 22 11:18:47 2019 -0500
```

It builds perfectly on Arch Linux of course. 

Poor Debian missed the train for just one day. I will build the latest version possible and try it out.

**Comment by substring** [comment]
Hi!
Have you tried since ? Looks like drmIsMaster was added in 2.4.98

**Comment by substring** [comment]
no feedback from OP
